# fly.toml app configuration file generated for ton-blockchain-mcp-remote on 2025-05-18T15:31:57+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ton-blockchain-mcp-remote'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
